### ISSUE TITLE
SimpleDB BatchDeleteAttributes Request is Malformed

### ISSUE THREAD

**Issue by thatjpk** [aio-libs/aiobotocore#11]
I'm attempting to use aiobotocore to do `batch_delete_attributes` requests to SimpleDB, but the request is kicked back as malformed.  A simple example that reproduces this based on the S3 example in the readme:

```python
import asyncio
import aiobotocore

AWS_ACCESS_KEY_ID = "xxx"
AWS_SECRET_ACCESS_KEY = "xxx"

@asyncio.coroutine
def go(loop):

    domain = 'sdb-domain-name'
    item_name = '234cbd5f48f7418b9b059d4817bf40fe'

    session = aiobotocore.get_session(loop=loop)
    client = session.create_client('sdb', region_name='us-east-1',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID)

    resp = yield from client.batch_delete_attributes(
        DomainName=domain,
        Items=[{'Name': item_name}]
    )
    print(resp)


loop = asyncio.get_event_loop()
loop.run_until_complete(go(loop))
```

When run, this outputs:

```
$ python test_async.py
Traceback (most recent call last):
  File "test_async.py", line 27, in <module>
    loop.run_until_complete(go(loop))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "test_async.py", line 21, in go
    Items=[{'Name': item_name}]
  File "/Users/jpk/virtualenvs/sdb-whack/src/aiobotocore-master/aiobotocore/client.py", line 132, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the BatchDeleteAttributes operation: The request is malformed
Unclosed connector
connector: <aiohttp.connector.TCPConnector object at 0x110c172e8>
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x110be9ba8>
transport: <_SelectorSocketTransport fd=10>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 698, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x110be9ba8>
transport: <_SelectorSocketTransport closing fd=10>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 698, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 624, in _process_write_backlog
    self._transport.write(chunk)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 702, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 590, in _fatal_error
    self._force_close(exc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 602, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 453, in call_soon
    handle = self._call_soon(callback, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 462, in _call_soon
    self._check_closed()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 289, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
$
```

However, the same code using botocore synchronously works:

```python
import asyncio
import aiobotocore
import botocore

AWS_ACCESS_KEY_ID = "xxx"
AWS_SECRET_ACCESS_KEY = "xxx"


def go():

    domain = 'sdb-domain-name'
    item_name = '234cbd5f48f7418b9b059d4817bf40fe'

    session = botocore.session.get_session()
    client = session.create_client('sdb', region_name='us-east-1',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID)

    resp = client.batch_delete_attributes(
        DomainName=domain,
        Items=[{'Name': item_name}]
    )
    print(resp)


go()
```

Which outputs:

```
{'ResponseMetadata': {'RequestId': '1ddaa063-51e4-3b4e-6257-10d3285bd61e', 'HTTPStatusCode': 200, 'BoxUsage': '0.0000219907'}}
```

For reference, the virtualenv this is running in looks like:

```
$ pip list
You are using pip version 6.1.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
aiobotocore (0.0.1, /Users/jpk/virtualenvs/sdb-whack/src/aiobotocore-master)
aiohttp (0.18.3)
appnope (0.1.0)
botocore (1.1.7)
chardet (2.3.0)
decorator (4.0.4)
docutils (0.12)
gnureadline (6.3.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
jmespath (0.7.1)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (6.1.1)
ptyprocess (0.5)
python-dateutil (2.4.2)
setuptools (15.0)
simplegeneric (0.8.1)
six (1.10.0)
traitlets (4.0.0)
$ python --version
Python 3.5.0
$
```

Am I doing something wrong, or is there a bug here?

**Comment by jettify** [comment]
Definitely bug, could you test new version? this bug should be fixed

**Comment by jettify** [comment]
Should be fixed in new version, please feel free to reopen if issue is still there.
