### ISSUE TITLE
s3.get_object(ChecksumMode='ENABLED') causes an exception

### ISSUE THREAD

**Issue by roy-ht** [aio-libs/aiobotocore#1125]
**Describe the bug**

Sample code:

```
import asyncio

import aiobotocore.session


async def main():
    session = aiobotocore.session.get_session()
    async with session.create_client("s3") as client:
        content = b"abc"
        bucket = "<...>"
        key = "temp/a.txt"
        await client.put_object(
            Bucket=bucket, Key=key, Body=content, ChecksumAlgorithm="sha1"
        )
        r = await client.get_object(Bucket=bucket, Key=key, ChecksumMode="ENABLED")
        await r["Body"].read()


if __name__ == "__main__":
    asyncio.run(main())
```

Result: 

```
Traceback (most recent call last):
  File "/home/jovyan/temp/a/test.py", line 20, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jovyan/temp/a/test.py", line 16, in main
    await r["Body"].read()
  File "/home/jovyan/temp/a/.venv/lib/python3.10/site-packages/botocore/httpchecksum.py", line 222, in read
    chunk = super().read(amt=amt)
  File "/home/jovyan/temp/a/.venv/lib/python3.10/site-packages/botocore/response.py", line 99, in read
    chunk = self._raw_stream.read(amt)
TypeError: ClientResponse.read() takes 1 positional argument but 2 were given
```

botocore version code (Success):

```
def main():
    session = botocore.session.get_session()
    client = session.create_client("s3")
    content = b"abc"
    bucket = "<...>"
    key = "temp/a.txt"
    client.put_object(Bucket=bucket, Key=key, Body=content, ChecksumAlgorithm="sha1")
    r = client.get_object(Bucket=bucket, Key=key, ChecksumMode="ENABLED")
    print(r["Body"].read())
```

**Checklist**
- [x] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

```
aiobotocore==2.13.1
aiohttp==3.9.5
aioitertools==0.11.0
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.2.0
botocore==1.34.131
frozenlist==1.4.1
idna==3.7
jmespath==1.0.1
multidict==6.0.5
python-dateutil==2.9.0.post0
six==1.16.0
urllib3==2.2.2
wrapt==1.16.0
yarl==1.9.4
```

**Environment:**
 - Python Version: 3.10.12
 - OS name and version: Ubuntu 22.04

**Additional context**

I guess aiohttp's ClientResponse.read() doesn't have an option "amt" while urllib3's response has it.

**Comment by thehesiod** [comment]
oh, this is a bigger problem than that, we're missing a whole subclass!

**Comment by thehesiod** [comment]
hmm, actually maybe we just missed to patch, since we already have `async def handle_checksum_body` (digging)

**Comment by thehesiod** [comment]
ty for the report!
