### ISSUE TITLE
check_for_200_error() AttributeError trying to set http_response.status_code

### ISSUE THREAD

**Issue by groner** [aio-libs/aiobotocore#190]
I hit this while uploading hundreds of thousands of files to S3 (full stack trace below):
```
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/botocore/handlers.py", line 85, in check_for_200_error
    http_response.status_code = 500
AttributeError: can't set attribute
```

This is using 0.2.2.

```
aiobotocore==0.2.2
aiohttp==1.3.5
async-timeout==1.2.0
botocore==1.5.0
chardet==3.0.2
docutils==0.13.1
jmespath==0.9.2
multidict==2.1.4
python-dateutil==2.6.0
six==1.10.0
yarl==0.9.8
```

All I have is the stack trace, and I don't have any easy way to reproduce it.

```
Traceback (most recent call last):
  File "/home/kai/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kai/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kai/syncer/syncer/__main__.py", line 53, in <module>
    loop.run_until_complete(main())
  File "/home/kai/.pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/home/kai/syncer/syncer/__main__.py", line 47, in main
    await sm.sync_subtree(args.src_root, args.bucket, args.dest_root)
  File "/home/kai/syncer/syncer/syncmaster.py", line 80, in sync_subtree
    lambda a: self.validate_or_upload(*a))))
  File "/home/kai/syncer/syncer/atools.py", line 23, in ajunk
    async for _ in aseq:
  File "/home/kai/syncer/syncer/syncmaster.py", line 343, in amap_with_flow
    yield await task
  File "/home/kai/syncer/syncer/syncmaster.py", line 247, in upload
    Parts=complete_parts,
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/aiobotocore/client.py", line 78, in _make_api_call
    operation_model, request_dict)
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 214, in _send_request
    exception)):
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 246, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/kai/syncer/.env/lib/python3.6/site-packages/botocore/handlers.py", line 85, in check_for_200_error
    http_response.status_code = 500
AttributeError: can't set attribute
```

**Comment by groner** [comment]
Without having dug in very much, it  seems like this might be hitting the  `ClientResponseProxy.status_code` read-only property.

**Comment by groner** [comment]
I'll see if I can't nail down the details with pdb.

**Comment by thehesiod** [comment]
Highly recommend checking out pycharm. Makes debugging a cinch :). Thanks for the report! I'm recovering from a surgery but will help if you guys don't figure it out by the time I'm better.

**Comment by thehesiod** [comment]
Highly recommend checking out pycharm. Makes debugging a cinch :). Thanks for the report! I'm recovering from a surgery but will help if you guys don't figure it out by the time I'm better.

**Comment by thehesiod** [comment]
Oh and know there's a known core Python SSL leak with certs that have CRLs in 3.5.3+. Will be resolved in next release of 3.xs.

**Comment by jettify** [comment]
Looks like @groner is right, botocore tries to patch `ClientResponseProxy.status_code` status code of request for reasons explained here:
https://github.com/boto/botocore/blob/1.5.0/botocore/handlers.py#L60-L85

We can add setter for `status_code`, but this looks very ugly.

**Comment by thehesiod** [comment]
Ugh. Sounds like we need to send a response proxy to botocore with getter and setter to make it mutable

**Comment by thehesiod** [comment]
I'll try to look at this soon, sorry for the delay, forgot about this!

**Comment by thehesiod** [comment]
looks like a simple fix, have a PR to fix this, @groner let me know if you'd like us roll a release with this fix.
