### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by errno** [aio-libs/aiobotocore#34]
When you try to run https://github.com/aio-libs/aiobotocore/blob/master/examples/simple.py on Python 3.5.1 it fails with:
```
Traceback (most recent call last):
  File "aiobot_test.py", line 36, in <module>
    loop.run_until_complete(go(loop))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "aiobot_test.py", line 19, in go
    aws_access_key_id=AWS_ACCESS_KEY_ID)
  File "/Users/gav/.virtualenvs/pred-service/src/aiobotocore/aiobotocore/session.py", line 47, in create_client
    client_config=config, api_version=api_version)
  File "/Users/gav/.virtualenvs/pred-service/lib/python3.5/site-packages/botocore/client.py", line 65, in create_client
    verify, credentials, scoped_config, client_config)
  File "/Users/gav/.virtualenvs/pred-service/src/aiobotocore/aiobotocore/client.py", line 101, in _get_client_args
    self._get_signature_version_and_region(
AttributeError: 'AioClientCreator' object has no attribute '_get_signature_version_and_region'
```

Unfortunately, it doesn't look like a bug in example, but rather bug in a library.

**Comment by jettify** [comment]
looks like botocore internals changed, in mean time you can use `botocore (1.3.26)`.

**Comment by jettify** [comment]
I pined botocore version in https://github.com/aio-libs/aiobotocore/pull/35

**Comment by jettify** [comment]
fixed
