### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectionError: Connection closed

### ISSUE THREAD

**Issue by jersobh** [aio-libs/aiobotocore#503]
From some days ago I've started receiving this error

Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "server.py", line 32, in middleware
    return await handler(request)
  File "server.py", line 39, in middleware_handler
    resp = await handler(request)
  File "/home/jeff/Projects/vidmonsters-api/controllers/media.py", line 211, in addMedia
    media['thumbnail'] = await uploadThumbnail(data['thumbnail'])
  File "/home/jeff/Projects/vidmonsters-api/controllers/media.py", line 311, in uploadThumbnail
    s3_upload = await client.put_object(Bucket=THUMBNAIL_BUCKET, Key=filename, Body=file)
  File "/usr/lib/python3.6/site-packages/aiobotocore/client.py", line 80, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 262, in _send_request
    request, operation_model, attempts)
  File "/usr/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 350, in _get_response
    operation_model)
  File "/usr/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 73, in convert_to_response_dict
    body = yield from http_response.read()
  File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 746, in read
    self._content = yield from self.content.read()
  File "/usr/lib/python3.6/site-packages/aiohttp/streams.py", line 607, in read
    return (yield from super().read(n))
  File "/usr/lib/python3.6/site-packages/aiohttp/streams.py", line 299, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed

**Comment by thehesiod** [comment]
have a reproducible in a testcase?  occasionally "bad stuff" occasionally happens with AWS API calls

**Comment by jettify** [comment]
Closing for now, feel free to reopen with more information.

**Comment by thehesiod** [comment]
btw just as an FYI, this can happen if your main thread gets blocked for a long time and doesn't service the connector, AWS will close it.

**Comment by jersobh** [comment]
It works fine at the server, just happens with localhost
