### ISSUE TITLE
SSL connection errors

### ISSUE THREAD

**Issue by ariwbolton** [aio-libs/aiobotocore#548]
# Issue

When trying to conduct a simple initial test (essentially adapted from [here](url)) , I'm getting `ssl.SSLError`s.

# Environment

Output from pip: `Successfully installed aiobotocore-0.6.0 aiohttp-3.0.7 botocore-1.8.21 idna-ssl-1.0.1 packaging-17.1 pyparsing-2.2.0 wrapt-1.10.11`

Using python 3.6.3 in macOS 10.12.6.

# Minimal Working Example

```python
"""Aiobotocore test."""
import asyncio
import aiobotocore

AWS_ACCESS_KEY_ID = '*****'
AWS_SECRET_ACCESS_KEY = '*****'


async def runner():
    session = aiobotocore.get_session()
    async with session.create_client(
        's3', region_name='us-east-1',
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        aws_access_key_id=AWS_ACCESS_KEY_ID
    ) as client:
        # upload object to amazon s3
        resp = await client.get_object(
            Bucket='****',
            Key='***'
        )

        print(resp)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    response = loop.run_until_complete(runner())

    print(response)
```

# Expected output

Response object, like normal

# Actual output

```Traceback (most recent call last):
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/connector.py", line 800, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 803, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 829, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "<project_root>/<file_path>.py", line 27, in <module>
    response = loop.run_until_complete(runner())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "<project_root>/<file_path>.py", line 19, in runner
    Key='all/1.wav'
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiobotocore/client.py", line 94, in _make_api_call
    operation_model, request_dict)
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 290, in _send_request
    exception)):
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 322, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "<project_root>/dev-env/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 352, in _get_response
    request.method, request.url, request.headers, request.body)
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 279, in _request
    timeout=None)
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/client.py", line 319, in _request
    traces=traces
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/connector.py", line 418, in connect
    traces=traces
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 223, in coro
    res = yield from await_meth()
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/connector.py", line 736, in _create_connection
    traces=None
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/connector.py", line 855, in _create_direct_connection
    raise last_exc
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/connector.py", line 838, in _create_direct_connection
    req=req, client_error=client_error)
  File "<project_root>/dev-env/lib/python3.6/site-packages/aiohttp/connector.py", line 805, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host s3.amazonaws.com:443 ssl:True [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]```

**Comment by jettify** [comment]
This is very odd, may be this issue related: https://github.com/aws/aws-cli/issues/1545

**Comment by jettify** [comment]
Most likely something related to your environment, can you try on clean env?

**Comment by ariwbolton** [comment]
```
$ virtualenv --clear test-env
...
$ pip install aiobotocore --no-cache-dir
...
$ pip list
aiobotocore (0.6.0)
aiohttp (3.0.7)
async-timeout (2.0.0)
attrs (17.4.0)
botocore (1.8.21)
chardet (3.0.4)
docutils (0.14)
idna (2.6)
idna-ssl (1.0.1)
jmespath (0.9.3)
multidict (4.1.0)
packaging (17.1)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
setuptools (38.5.2)
six (1.11.0)
wheel (0.30.0)
wrapt (1.10.11)
yarl (1.1.1)
```

and then running the test produces the same stack trace. Also, there doesn't appear to be anything out of the ordinary with my environment variables.

That issue does seem similar -- a couple of linked issues (aws/aws-cli#1499, and certifi/python-certifi#26) seem to indicate there is some issue between `certifi` and AWS (involving cross-signed certificates presented by AWS) but as far as I can tell, we're not using `certifi` here, or `python-requests` even.

I tried as much as messing with the global system-python installed packages (downgrading the version of `certifi` present there, as suggested in the linked issues), upgrading global awscli, and upgrading `botocore` to the most recent version in my test environment, all with no change in output. It also seems that my installed version of the awscli is working fine as well. Running `aws s3 ls` produces the expected output.

One thing I haven't tried is upgrading the version of OpenSSL that this project uses (it was suggested that perhaps OpenSSL was part of the problem), but to be perfectly honest I'm not sure how to get that done. Apparently `cryptography` uses it under the hood, and the suggested fix is to create a statically compiled wheel for it linked to the correct version of cryptography, but even then, it's "statically linked" to the correct version (prepackaged w/ the appropriate OpenSSL version I assume?),  and cryptography doesn't appear in the list of install packages... I'm not sure if it messing with that would even change anything.

**Comment by thehesiod** [comment]
is this an injection, does it happen in 0.5.3?

**Comment by thehesiod** [comment]
btw just tried this with my personal account, worked fine (although I used my `~/.aws/credentials` file for auth so I didn't need to pass my keys directly, and my bucket is in `us-west-2`.  Sounds like for some reason your system doesn't trust the certificates from `s3.amazonaws.com`.  Try this:
```bash
openssl s_client -connect s3.amazonaws.com:443
```
my openssl is:
```bash
amohr@amohr-macpro:/tmp$ openssl version
LibreSSL 2.2.7
```

**Comment by thehesiod** [comment]
btw I'm pretty sure this isn't related to aiobotocore/aiohttp.  I bet you can repro with `http.client` or botocore.  Could you in fact try with botocore?  That would rule us out :)

**Comment by thebenwaters** [comment]
@ariwbolton I had a similar issue after brew made python3 the default for ```brew install python```. Definitely try and follow the symlinks around.

https://stackoverflow.com/questions/18752409/updating-openssl-in-python-2-7

Also be careful and try not to destroy any critical paths.

This is for python2, but just try it with python3 maybe?

**Comment by JulienPalard** [comment]
@ariwbolton can you try specifying an up-to-date cert file, like:

```
$ python3 -m pip install certifi
$ export SSL_CERT_FILE="$(python3 -c 'import certifi; print(certifi.where())')"
$ python3 yourscript.py
```

Also telling us if it works with requests when installing `requests[security]`?

And giving us the result of:

```
import ssl
ssl.get_default_verify_paths()
```

and

```
import requests
requests.certs.where()
```

**Comment by JulienPalard** [comment]
@ariwbolton can you try specifying an up-to-date cert file, like:

```
$ python3 -m pip install certifi
$ export SSL_CERT_FILE="$(python3 -c 'import certifi; print(certifi.where())')"
$ python3 yourscript.py
```

Also telling us if it works with requests when installing `requests[security]`?

And giving us the result of:

```
import ssl
ssl.get_default_verify_paths()
```

and

```
import requests
requests.certs.where()
```

**Comment by jettify** [comment]
I do not think it is problem with aiobotocore, most likely environment issue. Thanks everyone for good suggestions! closing for now.

**Comment by bclodius** [comment]
Posting this here in case it helps others in future...

In my case all calls to AWS API's must go through corporate proxy.  I do not face this issue with typical synchronous boto3/botocore; but when using aiobotocore I face same issue as OP.

During client object creation you can pass kwarge `verify=False` to fix this issue.  Example snippet below.

```
    session = AioSession(profile=profile_name)
    async with session.create_client('iam', verify=False) as iam_client:
        paginator = iam_client.get_paginator('list_roles')
        async for page in paginator.paginate():
            for item in page.get('Roles', []):
                ...
```

**Comment by Camoen** [comment]
Was running into this issue trying to set up a Dask CloudProvider cluster. Resolved by exporting the SSL_CERT_FILE as an environmental variable.

```
import os
from dask_cloudprovider.aws import ECSCluster
os.environ["AWS_DEFAULT_REGION"] = 'us-west-2'
os.environ['SSL_CERT_FILE'] = '/etc/ssl/certs/ca-bundle.trust.crt'
cluster = ECSCluster(cluster_arn="")
```
