### ISSUE TITLE
get_credentials() fails on AioSession

### ISSUE THREAD

**Issue by TimOrme** [aio-libs/aiobotocore#553]
Using aiobotocore 0.6.0, python 3.6.3

Executing:

```python
aiobotocore.get_session().get_credentials().secret_key
```

Fails with the following error:

```aiobotocore.get_session().get_credentials().secret_key
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/venv/lib/python3.6/site-packages/botocore/credentials.py", line 336, in secret_key
    self._refresh()
  File "/venv/lib/python3.6/site-packages/botocore/credentials.py", line 415, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/venv/lib/python3.6/site-packages/botocore/credentials.py", line 431, in _protected_refresh
    metadata = self._refresh_using()
  File "/venv/lib/python3.6/site-packages/botocore/credentials.py", line 555, in fetch_credentials
    return self._get_cached_credentials()
  File "/venv/lib/python3.6/site-packages/botocore/credentials.py", line 566, in _get_cached_credentials
    self._write_to_cache(response)
  File "/venv/lib/python3.6/site-packages/botocore/credentials.py", line 591, in _write_to_cache
    self._cache[self._cache_key] = deepcopy(response)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle generator objects```

When hitting the AssumeRoleProvider. It appears that the provider tries to write the client to cache but fails to serialize the Aio client.

**Comment by thehesiod** [comment]
may be related to this: https://github.com/aio-libs/aiobotocore/issues/551#issuecomment-375816256.  Mind trying earlier versions of aiohttp?

**Comment by jettify** [comment]
I think problem more tricky check this lines:
https://github.com/boto/botocore/blob/5e044f7b94acb83fce4265b5ce47620db70a9876/botocore/credentials.py#L683-L687
botocore create async client and tries to do request, but that fails because no `await` as result coroutine never executed.

**Comment by jettify** [comment]
https://github.com/aio-libs/aiobotocore/blob/52df9fc4b4eaf8145b2512b9daac312d3539232c/aiobotocore/endpoint.py#L86-L117

May be not directly related but `self.__response.close()`should coroutine right for new aiohttp?

**Comment by TimOrme** [comment]
As @jettify said, the problem is that the call to retrieve credentials doesn't await, and instead returns the generator itself, which it can't serialize into its cache.  I tried this with aiohttp 3.0.9, which should be supported I think?

**Comment by yunstanford** [comment]
it might also requires to convert `create_client` to `async def` as it calls here, https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/session.py#L65, it'd be incompatible change.

**Comment by thehesiod** [comment]
will check now

**Comment by thehesiod** [comment]
looks like in 0.8.0 with the new botocore this isn't an issue, just tried now and got my creds.  Really this shouldn't require a client because there are no AWS calls to make to get your creds, it would kinda defeat the purpose :)  Sounds like bad botocore impl from before.

**Comment by thehesiod** [comment]
note the restructured test for the 0.8.0 release passed w/o warnings: https://travis-ci.org/aio-libs/aiobotocore/jobs/376056214

**Comment by yunstanford** [comment]
Thanks, will take a look.

**Comment by thehesiod** [comment]
this is what I was alluding to btw: https://github.com/aio-libs/aiobotocore/issues/2

**Comment by thehesiod** [comment]
ah, I see, I'm not hitting this because I'm using a ~/.aws/credentials file.  @yunstanford  know how to trigger this workflow?

**Comment by thehesiod** [comment]
yay, I figured out how to reproduce this

**Comment by thehesiod** [comment]
oh gawd, this ties into https://github.com/aio-libs/aiobotocore/issues/2, basically the whole Credentials class may need to get replaced, this is going to be a BIG job.

**Comment by thehesiod** [comment]
for those wanting to test this, follow: https://boto3.readthedocs.io/en/latest/guide/configuration.html#assume-role-provider

**Comment by thehesiod** [comment]
so here's why this is a HUGE job.

`RefreshableCredentials.[secret_key,access_key,token]` properties call `self._refresh()`, and this method needs to be made async so that later on `AssumeRoleCredentialFetcher._get_credentials` can be awaited.  The problem is that you can't simply make these properties async methods as they're called all over the place.  We'll need a strategy for how to attack this.  Further we should attack `InstanceMetadataFetcher._get_request` as well.

**Comment by thehesiod** [comment]
temp monkeypatch fix: 
```
orig_create_client = botocore.credentials.AssumeRoleCredentialFetcher._create_client


def _create_client(self):
    frozen_credentials = self._source_credentials.get_frozen_credentials()
    if not getattr(self, '_boto_session', None):
        self._boto_session = botocore.session.Session()

    return self._boto_session.create_client(
        'sts',
        aws_access_key_id=frozen_credentials.access_key,
        aws_secret_access_key=frozen_credentials.secret_key,
        aws_session_token=frozen_credentials.token,
    )

botocore.credentials.AssumeRoleCredentialFetcher._create_client = _create_client
```
