### ISSUE TITLE
unable to create session

### ISSUE THREAD

**Issue by oba11** [aio-libs/aiobotocore#630]
I'm not sure if I'm doing something wrong but tried to execute the [example script](https://raw.githubusercontent.com/aio-libs/aiobotocore/master/examples/simple.py) but the below error

```
Traceback (most recent call last):
  File "chalicelib/s3.py", line 36, in <module>
    loop.run_until_complete(go(loop))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "chalicelib/s3.py", line 18, in go
    aws_access_key_id=AWS_ACCESS_KEY_ID)
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/session.py", line 76, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/client.py", line 42, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/args.py", line 67, in get_client_args
    connector_args=new_config.connector_args)
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 363, in create_endpoint
    loop=self._loop, connector_args=connector_args)
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 154, in __init__
    max_pool_connections=max_pool_connections)
TypeError: __init__() got an unexpected keyword argument 'proxies'
```

```
python --version
Python 3.6.6

aiobotocore     0.9.4
botocore        1.11.6

```

**Comment by oba11** [comment]
Figure out the issue, the botocore wasnt compabilty. Had `aws-xray-sdk` in my requirements as well, downgraded x-ray to `aws-xray-sdk==1.1` and it worked.
Thanks

**Comment by thehesiod** [comment]
ahh, let us know if you want us to add aws-xray-sdk to the list of extras: https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L26

**Comment by oba11** [comment]
@thehesiod I think it's okay with those 2 (awscli and boto3), else the extra might end up being a huge list. Thank you
