### ISSUE TITLE
Async file io using aiofiles

### ISSUE THREAD

**Issue by conraddd** [aio-libs/aiobotocore#746]
Anyone tried using put_object() with [aiofiles](https://github.com/Tinche/aiofiles) before? What I want to achieve is non-blocking file io when uploading file to aws s3. Seems the only option is to use aiofiles to handle file io. However I got error when I do so.

Here is the code
```Python
async def upload_file(file_path, key)
    f = await aiofiles.open(file_path, "rb")
    resp = await s3_client.put_object(Bucket="SOME_BUCKET",
                                        Key=key,
                                        Body=f)
    await f.close()

```
 Error
```
Traceback (most recent call last):
  File "/tmp/util/util_new.py", line 44, in upload_file
    Body=f)
  File "/usr/local/lib/python3.7/dist-packages/aiobotocore/client.py", line 83, in _make_api_call
    request_signer=self._request_signer, context=request_context)
  File "/usr/local/lib/python3.7/dist-packages/botocore/hooks.py", line 360, in emit_until_response
    return self._emitter.emit_until_response(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/hooks.py", line 243, in emit_until_response
    responses = self._emit(event_name, kwargs, stop_on_response=True)
  File "/usr/local/lib/python3.7/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/handlers.py", line 212, in conditionally_calculate_md5
    calculate_md5(params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/handlers.py", line 190, in calculate_md5
    binary_md5 = _calculate_md5_from_file(body)
  File "/usr/local/lib/python3.7/dist-packages/botocore/handlers.py", line 204, in _calculate_md5_from_file
    md5.update(chunk)
TypeError: object supporting the buffer API required

```

**Comment by thehesiod** [comment]
It won't help as I discovered because botocore needs to read the whole file
to calculate it's md5. Unless you're talking about a network drive that can
be slow reading

**Comment by thehesiod** [comment]
btw here is how I did it to support a regular file in chunks:
```python
            try:
                aiohttp.payload.PAYLOAD_REGISTRY.get(csv_f)
            except aiohttp.payload.LookupError:
                aiohttp.payload.PAYLOAD_REGISTRY.register(aiohttp.payload.BytesIOPayload, tempfile.SpooledTemporaryFile)

            logger.info(f"Uploading csv for {table_name} to {csv_path}")
            csv_f.seek(0)
            await s3_client.put_object(Bucket=settings.REDSHIFT_EXTRACTS_BUCKET, Key=str(csv_path), Body=csv_f)
```
As long as it's not a network drive this should work well.  I'll investigate the aiofiles thing, but I think it's going to involve a ton of work

**Comment by terrycain** [comment]
The other option is to do a multipart upload (assuming the file is bigger than 5MiB), that way it wont read the entire file to calculate the MD5. s3.upload_file does this i believe.

**Comment by thehesiod** [comment]
btw I misspoke about memory because the md5 calculation happens in 1MB chunks
