### ISSUE TITLE
got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by potatochip** [aio-libs/aiobotocore#807]
**Describe the bug**
I get the following exception when awaiting the `s3_put` coro below. This works fine on the first run of a process using something akin to asyncio.run, but fails on a subsequent run when the original loop has been closed and a new one created. Maybe this is related to the session object not taking a loop param anymore? I assume it would go away if I recreate a new session object each call, but is that intended?

```python
_REGION = None
_SESSION = None


def get_aws_region() -> str:
    """Get the aws region of the current ec2 machine."""
    global _REGION
    if _REGION is None:
        try:
            _REGION = ec2_metadata.region
        except (ConnectionError, ConnectTimeout):
            _REGION = 'us-east-1'
    return _REGION


def get_s3_client() -> aiobotocore.client.AioBaseClient:
    """Get async context client for s3."""
    global _SESSION
    if _SESSION is None:
        _SESSION = aiobotocore.get_session()
    return _SESSION.create_client(
        's3',
        region_name=get_aws_region(),
        config=Config(signature_version='s3v4'))


async def s3_put(bucket: str, key: str, body: str) -> None:
    """Async put body into key on s3.

    This is just a wrapper around put_object enforcing encryption.
    """
    async with get_s3_client() as client:
        await client.put_object(Bucket=bucket,
                                Key=key,
                                Body=body,
                                ServerSideEncryption='AES256') 
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/client.py", line 111, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/client.py", line 131, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/endpoint.py", line 84, in _send_request
    request = await self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/endpoint.py", line 77, in create_request
    await self._event_emitter.emit(event_name, request=request,
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/hooks.py", line 27, in _emit
    response = await handler(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/signers.py", line 16, in handler
    return await self.sign(operation_name, request)
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/signers.py", line 53, in sign
    auth = await self.get_auth_instance(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/signers.py", line 75, in get_auth_instance
    frozen_credentials = await self._credentials.get_frozen_credentials()
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/credentials.py", line 290, in get_frozen_credentials
    await self._refresh()
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/credentials.py", line 257, in _refresh
    async with self._refresh_lock:
  File "/usr/local/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-59191' coro=<App._process_file() running at x> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.8/asyncio/tasks.py:751]> got Future <Future pending> attached to a different loop
```

**pip freeze results**

```
aiobotocore==1.0.4
aiohttp==3.6.2
aioitertools==0.6.1
aioredis==1.3.1
async-timeout==3.0.1
asyncssh==2.1.0
attrs==19.3.0
boto3==1.12.32
botocore==1.15.32
cached-property==1.5.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
datadog==0.35.0
decorator==4.4.2
docutils==0.15.2
ec2-metadata==2.1.0
hiredis==1.0.1
idna==2.9
jmespath==0.9.5
multidict==4.7.5
plac==1.1.3
psycopg2-binary==2.8.5
pycparser==2.20
python-dateutil==2.8.1
python-json-logger==0.1.11
requests==2.23.0
s3transfer==0.3.3
six==1.14.0
SQLAlchemy==1.3.16
street-cred==0.0.2
urllib3==1.25.9
wrapt==1.12.1
yarl==1.4.2
```

**Environment:**
 - Python Version: 3.8.2
 - OS name and version: Debian GNU/Linux 10 (buster)

**Comment by thehesiod** [comment]
you can't create a client/session from one loop and use in another, it's just not allowed in general in asyncio of mixing objects between loops.  Feel free to re-open if I'm missing something
