### ISSUE TITLE
Timestream: Query fails

### ISSUE THREAD

**Issue by DrBomb** [aio-libs/aiobotocore#902]
**Describe the bug**
After creating a timestream client, making a query rises a TypeError plus a "Coroutine was never awaited"
Using the sampleDB on timestream, here's a sample code

```
import asyncio
from aiobotocore.session import get_session

async def main():
    session = get_session()
    async with session.create_client('timestream-query', region_name="us-west-2") as timestream:
        result = await timestream.query(
            QueryString='''SELECT
    truck_id,
    fleet,
    fuel_capacity,
    model,
    load_capacity,
    make,
    measure_name
FROM "sampleDB".IoT
GROUP BY truck_id, fleet, fuel_capacity, model, load_capacity, make, measure_name'''
        )

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Here's the result:

```
//test.py:20: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "//test.py", line 21, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "//test.py", line 7, in main
    result = await timestream.query(
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/client.py", line 141, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/client.py", line 161, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 77, in _send_request
    request = await self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 70, in create_request
    await self._event_emitter.emit(event_name, request=request,
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/discovery.py", line 242, in discover_endpoint
    endpoint = self._manager.describe_endpoint(
  File "/usr/local/lib/python3.10/site-packages/botocore/discovery.py", line 194, in describe_endpoint
    endpoints = self._refresh_current_endpoints(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/discovery.py", line 154, in _refresh_current_endpoints
    endpoints = self._parse_endpoints(response)
  File "/usr/local/lib/python3.10/site-packages/botocore/discovery.py", line 110, in _parse_endpoints
    endpoints = response['Endpoints']
TypeError: 'coroutine' object is not subscriptable
sys:1: RuntimeWarning: coroutine 'AioBaseClient._make_api_call' was never awaited
```

**Checklist**
- [X] I have reproduced in environment where `pip check` passes without errors
- [X] I have provided `pip freeze` results
- [X] I have provided sample code or detailed way to reproduce
- [X] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze**
```
aiobotocore==2.0.0
aiohttp==3.8.1
aioitertools==0.8.0
aiosignal==1.2.0
async-timeout==4.0.1
attrs==21.2.0
botocore==1.22.8
charset-normalizer==2.0.7
rozenlist==1.2.0
idna==3.3
jmespath==0.10.0
multidict==5.2.0
python-dateutil==2.8.2
six==1.16.0
typing_extensions==4.0.0
urllib3==1.26.7
wrapt==1.13.3
yarl==1.7.2
```

**Environment:**
 - Python Version: 3.9.2, 3.10.0
 - OS name and version: Discovered on Windows 10. Reproduced on docker image `python:latest`

**Additional context**
Perhaps related to #707 ?

**Comment by thehesiod** [comment]
due to new codepath that needed to be async'ified
