### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by dacevedo12** [aio-libs/aiobotocore#929]
**Describe the bug**
Long running tasks report an exception raised by aiohttp. This didn't happen with aiobotocore 1.0.4

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [x] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**
- aioboto3==9.5.0
- aiobotocore==2.2.0
- aiohttp==3.8.1

**Environment:**
 - Python Version: 3.9
 - OS name and version: nixos 2.6.0

**Relevant log**
```
Traceback (most recent call last):
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 171, in send
    resp = await self._session.request(
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:
  File "/nix/store/mk49bbilz7426y2sqvr8jvh7zzly9s9y-src/dynamodb/operations.py", line 413, in update_item
    await table_resource.update_item(**_exclude_none(args=args))
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aioboto3/resources/factory.py", line 269, in do_action
    response = await action(self, *args, **kwargs)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aioboto3/resources/action.py", line 42, in __call__
    response = await getattr(parent.meta.client, operation_name)(*args, **params)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/client.py", line 214, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/client.py", line 234, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 83, in _send_request
    while await self._needs_retry(attempts, operation_model,
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 221, in _needs_retry
    responses = await self._event_emitter.emit(
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/botocore/retryhandler.py", line 192, in __call__
    if self._checker(**checker_kwargs):
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/botocore/retryhandler.py", line 265, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/botocore/retryhandler.py", line 284, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/botocore/retryhandler.py", line 331, in __call__
    checker_response = checker(attempt_number, response,
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/botocore/retryhandler.py", line 231, in __call__
    return self._check_caught_exception(
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/botocore/retryhandler.py", line 374, in _check_caught_exception
    raise caught_exception
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 152, in _do_get_response
    http_response = await self._send(request)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 237, in _send
    return await self.http_session.send(request)
  File "/nix/store/m8iacsxjzf9763h4sxgr8hj4dkid8jfs/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 202, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: [Errno 32] Broken pipe
```

**Comment by thehesiod** [comment]
hmm, i wonder if this is another missing retry due to the exception mapping

**Comment by thehesiod** [comment]
no, ClientOSError is a subclass of ClientConnectionError which is retryable.  Can you add debug logging to see if it's retrying?  It could be too that this particular API is not retryable

**Comment by dacevedo12** [comment]
Haven't had the time to debug it but it should be retryable, it didn't happen in previous versions

Reverting to aioboto3: 8.0.3 + aiobotocore: 1.0.4 meanwhile

**Comment by dacevedo12** [comment]
Tried again with aioboto3 9.6.0 + aiobotocore 2.3.0 + setting the retry mode to 'standard' and it no longer fails.

Probably https://github.com/aio-libs/aiobotocore/issues/940#issuecomment-1127152120 had something to do with this as well
